/**
 * AgriFresh - 100+ Agriculture, Fresh Fruits, Vegetables, Seeds & Farming Tools Seed Catalog
 *
 * Categories:
 *  1. Fresh Fruits      (Apples & Pears, Mangoes & Tropical, Berries & Grapes, Citrus & Watermelon)
 *  2. Fresh Vegetables  (Leafy Greens, Daily Essentials, Exotic & Salad, Root & Squash)
 *  3. Seeds & Saplings  (Crop Seeds, Vegetable Seeds, Fruit Saplings, Garden Seeds)
 *  4. Farming Tools     (Irrigation & Sprayers, Cutting & Pruning, Soil Testing & Care, Farm Protection)
 *  5. Organic Staples   (Ghee & Oils, Honey & Sweeteners, Grains & Flours, Spices & Pulses)
 */

const seedCatalogData = [
  // ── 1. FRESH FRUITS ────────────────────────────────────────────────────────
  // Apples & Pears
  {
    name: "Organic Shimla Red Apples",
    title: "Crisp & Juicy Organic Shimla Red Apples (1 kg)",
    description: "Hand-picked directly from the high-altitude orchards of Shimla. Sweet, crunchy, and rich in natural antioxidants.",
    price: 180,
    comparePrice: 220,
    category: "Fresh Fruits",
    subcategory: "Apples & Pears",
    brand: "Himalayan Orchards",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Shimla, Himachal Pradesh",
    stock: 120,
    rating: 4.9,
    numReviews: 145,
    isFeatured: true,
    images: [{ public_id: "frt1", url: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=600&q=80", altText: "Shimla Red Apples" }],
    isActive: true
  },
  {
    name: "Royal Gala Apples",
    title: "Premium Royal Gala Fresh Apples (1 kg)",
    description: "Imported crisp Royal Gala apples with sweet floral aroma, thin skin, and satisfying crunch.",
    price: 210,
    comparePrice: 250,
    category: "Fresh Fruits",
    subcategory: "Apples & Pears",
    brand: "FreshFarm Global",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Kashmir Valley",
    stock: 85,
    rating: 4.8,
    numReviews: 92,
    images: [{ public_id: "frt2", url: "https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&w=600&q=80", altText: "Royal Gala Apples" }],
    isActive: true
  },
  {
    name: "Green Packham Pears",
    title: "Sweet & Tender Packham Pears (1 kg)",
    description: "Butter-soft, aromatic green pears brimming with natural dietary fiber and refreshing juice.",
    price: 160,
    comparePrice: 190,
    category: "Fresh Fruits",
    subcategory: "Apples & Pears",
    brand: "Organic Valley",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Kotgarh, Himachal Pradesh",
    stock: 60,
    rating: 4.7,
    numReviews: 64,
    images: [{ public_id: "frt3", url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80", altText: "Green Pears" }],
    isActive: true
  },

  // Mangoes & Tropical
  {
    name: "Ratnagiri Alphonso Mangoes",
    title: "Original GI-Tagged Ratnagiri Alphonso Mangoes (1 Dozen / ~3kg)",
    description: "King of Mangoes naturally tree-ripened without any chemicals or carbide. Rich golden flesh with unforgettable sweetness.",
    price: 1250,
    comparePrice: 1500,
    category: "Fresh Fruits",
    subcategory: "Mangoes & Tropical",
    brand: "Devgad Farms",
    unit: "1 Dozen",
    isOrganic: true,
    farmOrigin: "Ratnagiri, Maharashtra",
    stock: 45,
    rating: 5.0,
    numReviews: 230,
    isFeatured: true,
    images: [{ public_id: "frt4", url: "https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80", altText: "Alphonso Mangoes" }],
    isActive: true
  },
  {
    name: "Organic Hass Avocados",
    title: "Creamy Hass Avocados (2 Pcs / ~400g)",
    description: "Nutrient-dense creamy Hass avocados packed with healthy heart fats, vitamin E, and potassium.",
    price: 240,
    comparePrice: 290,
    category: "Fresh Fruits",
    subcategory: "Mangoes & Tropical",
    brand: "Coorg Organics",
    unit: "2 Pcs",
    isOrganic: true,
    farmOrigin: "Coorg, Karnataka",
    stock: 75,
    rating: 4.8,
    numReviews: 110,
    images: [{ public_id: "frt5", url: "https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=600&q=80", altText: "Hass Avocados" }],
    isActive: true
  },
  {
    name: "Red Dragon Fruit",
    title: "Fresh Pink Skin Red Flesh Dragon Fruit (1 kg)",
    description: "Vibrant pitaya high in fiber, magnesium, and vitamin C with subtle sweet kiwi-like texture.",
    price: 220,
    comparePrice: 260,
    category: "Fresh Fruits",
    subcategory: "Mangoes & Tropical",
    brand: "Sunshine Farms",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Gujarat Farms",
    stock: 50,
    rating: 4.7,
    numReviews: 88,
    images: [{ public_id: "frt6", url: "https://images.unsplash.com/photo-1527325678964-54921646f988?auto=format&fit=crop&w=600&q=80", altText: "Red Dragon Fruit" }],
    isActive: true
  },

  // Berries & Grapes
  {
    name: "Farm Fresh Mahabaleshwar Strawberries",
    title: "Sweet Organic Mahabaleshwar Strawberries (250g Pack)",
    description: "Deep red juicy strawberries harvested early morning to retain peak freshness and heavenly berry aroma.",
    price: 130,
    comparePrice: 160,
    category: "Fresh Fruits",
    subcategory: "Berries & Grapes",
    brand: "Mahabaleshwar Berries",
    unit: "250g Pack",
    isOrganic: true,
    farmOrigin: "Mahabaleshwar, Maharashtra",
    stock: 90,
    rating: 4.9,
    numReviews: 178,
    isFeatured: true,
    images: [{ public_id: "frt7", url: "https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=600&q=80", altText: "Fresh Strawberries" }],
    isActive: true
  },
  {
    name: "Nashik Green Seedless Grapes",
    title: "Sweet Crisp Green Seedless Grapes (500g)",
    description: "Plump seedless table grapes from Nashik vineyards. Bursting with natural sugars and refreshing hydration.",
    price: 90,
    comparePrice: 120,
    category: "Fresh Fruits",
    subcategory: "Berries & Grapes",
    brand: "Nashik Vineyards",
    unit: "500g",
    isOrganic: true,
    farmOrigin: "Nashik, Maharashtra",
    stock: 110,
    rating: 4.8,
    numReviews: 154,
    images: [{ public_id: "frt8", url: "https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80", altText: "Green Seedless Grapes" }],
    isActive: true
  },

  // Citrus & Watermelon
  {
    name: "Nagpur Juicy Oranges",
    title: "Sweet & Tangy Nagpur Oranges (1 kg)",
    description: "Famous Nagpur oranges rich in immune-boosting Vitamin C, dietary fiber, and refreshing natural juice.",
    price: 110,
    comparePrice: 140,
    category: "Fresh Fruits",
    subcategory: "Citrus & Watermelon",
    brand: "Orange Valley",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Nagpur, Maharashtra",
    stock: 140,
    rating: 4.7,
    numReviews: 126,
    images: [{ public_id: "frt9", url: "https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?auto=format&fit=crop&w=600&q=80", altText: "Nagpur Oranges" }],
    isActive: true
  },
  {
    name: "Organic Red Pomegranate",
    title: "Ruby Red Seed Pomegranate (1 kg)",
    description: "Deep red juicy pomegranate seeds loaded with powerful antioxidants, polyphenols, and iron.",
    price: 195,
    comparePrice: 230,
    category: "Fresh Fruits",
    subcategory: "Citrus & Watermelon",
    brand: "Deccan Agrotech",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Solapur, Maharashtra",
    stock: 80,
    rating: 4.8,
    numReviews: 95,
    images: [{ public_id: "frt10", url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80", altText: "Red Pomegranate" }],
    isActive: true
  },

  // ── 2. FRESH VEGETABLES ───────────────────────────────────────────────────
  // Leafy Greens
  {
    name: "Organic Farm Spinach (Palak)",
    title: "Fresh Harvest Organic Spinach / Palak (250g Bunch)",
    description: "Tender green spinach leaves cultivated without synthetic pesticides. Rich in iron, folate, and essential vitamins.",
    price: 35,
    comparePrice: 45,
    category: "Fresh Vegetables",
    subcategory: "Leafy Greens",
    brand: "GreenLeaf Organics",
    unit: "250g Bunch",
    isOrganic: true,
    farmOrigin: "Local Organic Farm",
    stock: 150,
    rating: 4.8,
    numReviews: 210,
    isFeatured: true,
    images: [{ public_id: "veg1", url: "https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=600&q=80", altText: "Organic Spinach" }],
    isActive: true
  },
  {
    name: "Hydroponic Romaine Lettuce",
    title: "Crisp Hydroponic Romaine Lettuce Head (200g)",
    description: "Pesticide-free hydroponically grown Romaine lettuce with super crunchy leaves, ideal for fresh Caesar salads.",
    price: 65,
    comparePrice: 85,
    category: "Fresh Vegetables",
    subcategory: "Leafy Greens",
    brand: "Urban HydroFarms",
    unit: "200g Head",
    isOrganic: true,
    farmOrigin: "Pune Hydroponic Greenhouse",
    stock: 70,
    rating: 4.9,
    numReviews: 98,
    images: [{ public_id: "veg2", url: "https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?auto=format&fit=crop&w=600&q=80", altText: "Romaine Lettuce" }],
    isActive: true
  },

  // Daily Essentials
  {
    name: "Farm Fresh Vine Tomatoes",
    title: "Organic Red Country Tomatoes (1 kg)",
    description: "Sun-ripened red vine tomatoes cultivated organically. Juicy, tangy, and essential for every kitchen.",
    price: 45,
    comparePrice: 60,
    category: "Fresh Vegetables",
    subcategory: "Daily Essentials",
    brand: "AgriFresh Direct",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Kolar, Karnataka",
    stock: 200,
    rating: 4.7,
    numReviews: 340,
    isFeatured: true,
    images: [{ public_id: "veg3", url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80", altText: "Vine Tomatoes" }],
    isActive: true
  },
  {
    name: "Organic Red Onions",
    title: "Premium Nasik Red Onions (1 kg)",
    description: "Firm, crisp Nashik red onions with sharp aroma and long shelf life. Grown using traditional compost methods.",
    price: 40,
    comparePrice: 55,
    category: "Fresh Vegetables",
    subcategory: "Daily Essentials",
    brand: "Nashik Produce",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Nashik, Maharashtra",
    stock: 250,
    rating: 4.8,
    numReviews: 290,
    images: [{ public_id: "veg4", url: "https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80", altText: "Red Onions" }],
    isActive: true
  },
  {
    name: "Farm New Crop Potatoes",
    title: "Fresh Soil-Free Farm Potatoes (1 kg)",
    description: "Smooth skinned, starchy golden potatoes direct from Punjab farms. Perfect for baking, frying, and curry.",
    price: 35,
    comparePrice: 45,
    category: "Fresh Vegetables",
    subcategory: "Daily Essentials",
    brand: "Punjab AgriFarms",
    unit: "1 kg",
    isOrganic: true,
    farmOrigin: "Jalandhar, Punjab",
    stock: 300,
    rating: 4.6,
    numReviews: 180,
    images: [{ public_id: "veg5", url: "https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80", altText: "Farm Potatoes" }],
    isActive: true
  },

  // Exotic & Salad
  {
    name: "Trio Colored Bell Peppers",
    title: "Fresh Red, Yellow & Green Bell Peppers (500g Pack)",
    description: "Vibrant greenhouse grown capsicums packed with beta-carotene, crunchy texture, and sweet flavor.",
    price: 110,
    comparePrice: 140,
    category: "Fresh Vegetables",
    subcategory: "Exotic & Salad",
    brand: "Greenhouse Elite",
    unit: "500g Pack",
    isOrganic: true,
    farmOrigin: "Polyhouse Farms",
    stock: 85,
    rating: 4.9,
    numReviews: 142,
    isFeatured: true,
    images: [{ public_id: "veg6", url: "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?auto=format&fit=crop&w=600&q=80", altText: "Trio Bell Peppers" }],
    isActive: true
  },
  {
    name: "Fresh Broccoli Florets",
    title: "Organic Fresh Green Broccoli Head (500g)",
    description: "Compact green broccoli heads dense with vitamins K and C, sulforaphane, and plant nutrients.",
    price: 80,
    comparePrice: 100,
    category: "Fresh Vegetables",
    subcategory: "Exotic & Salad",
    brand: "Cool Harvest",
    unit: "500g",
    isOrganic: true,
    farmOrigin: "Ooty Orchards",
    stock: 95,
    rating: 4.8,
    numReviews: 115,
    images: [{ public_id: "veg7", url: "https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?auto=format&fit=crop&w=600&q=80", altText: "Green Broccoli" }],
    isActive: true
  },
  {
    name: "Button Mushrooms Pack",
    title: "Fresh White Button Mushrooms (200g Tray)",
    description: "Hygienically cultivated white button mushrooms, rich in selenium, vitamin D, and umami savory flavor.",
    price: 55,
    comparePrice: 70,
    category: "Fresh Vegetables",
    subcategory: "Exotic & Salad",
    brand: "Alpine Mushrooms",
    unit: "200g Tray",
    isOrganic: true,
    farmOrigin: "Solan, Himachal Pradesh",
    stock: 100,
    rating: 4.7,
    numReviews: 87,
    images: [{ public_id: "veg8", url: "https://images.unsplash.com/photo-1504470695779-75300268aa0e?auto=format&fit=crop&w=600&q=80", altText: "Button Mushrooms" }],
    isActive: true
  },

  // ── 3. SEEDS & SAPLINGS ───────────────────────────────────────────────────
  // Crop & Vegetable Seeds
  {
    name: "High-Yield Hybrid Wheat Seeds",
    title: "HD-2967 High Yield Disease-Resistant Wheat Seeds (5 kg Bag)",
    description: "Certified high-germination wheat seed variety with strong tillering capacity, rust resistance, and superior grain quality.",
    price: 450,
    comparePrice: 550,
    category: "Seeds & Saplings",
    subcategory: "Crop Seeds",
    brand: "AgriSeeds Corp",
    unit: "5 kg Bag",
    isOrganic: false,
    farmOrigin: "IARI Certified Research Station",
    stock: 80,
    rating: 4.9,
    numReviews: 95,
    isFeatured: true,
    images: [{ public_id: "sed1", url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80", altText: "Wheat Seeds" }],
    isActive: true
  },
  {
    name: "Organic Vegetable Seed Starter Kit",
    title: "Complete 15-in-1 Organic Kitchen Garden Seed Kit",
    description: "Includes Non-GMO seeds for Tomato, Spinach, Coriander, Chili, Cucumber, Brinjal, Radish, Beans & Capsicum with planting guide.",
    price: 299,
    comparePrice: 450,
    category: "Seeds & Saplings",
    subcategory: "Vegetable Seeds",
    brand: "GreenThumb Seeds",
    unit: "15 Packets Kit",
    isOrganic: true,
    farmOrigin: "Organic Seed Bank",
    stock: 120,
    rating: 4.8,
    numReviews: 165,
    isFeatured: true,
    images: [{ public_id: "sed2", url: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=600&q=80", altText: "Vegetable Seed Kit" }],
    isActive: true
  },
  {
    name: "Hybrid Cherry Tomato Seeds",
    title: "Red Ruby Hybrid Cherry Tomato Seeds (100 Seeds Pack)",
    description: "High yield indeterminate cherry tomato variety producing sweet mini fruits continuously over 6 months.",
    price: 149,
    comparePrice: 199,
    category: "Seeds & Saplings",
    subcategory: "Vegetable Seeds",
    brand: "Seminis Agri",
    unit: "100 Seeds Pack",
    isOrganic: true,
    farmOrigin: "Bangalore Seed Lab",
    stock: 200,
    rating: 4.7,
    numReviews: 82,
    images: [{ public_id: "sed3", url: "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80", altText: "Cherry Tomato Seeds" }],
    isActive: true
  },

  // Fruit Saplings
  {
    name: "Grafted Thai Guava Live Plant Sapling",
    title: "All-Season Grafted VNR Bihi Thai Guava Live Plant Sapling",
    description: "Fast fruiting high-density guava sapling producing large sweet crisp guavas weighing up to 500g each within 1 year.",
    price: 349,
    comparePrice: 450,
    category: "Seeds & Saplings",
    subcategory: "Fruit Saplings",
    brand: "NurseryCraft",
    unit: "1 Live Plant",
    isOrganic: true,
    farmOrigin: "Kolkata Plant Nursery",
    stock: 40,
    rating: 4.9,
    numReviews: 74,
    images: [{ public_id: "sed4", url: "https://images.unsplash.com/photo-1501004318641-b39e6451bec6?auto=format&fit=crop&w=600&q=80", altText: "Guava Plant Sapling" }],
    isActive: true
  },

  // ── 4. FARMING TOOLS ───────────────────────────────────────────────────────
  // Irrigation & Sprayers
  {
    name: "16 Litre Battery Powered Knapsack Sprayer",
    title: "16L Rechargeable Electric Farm Agricultural Sprayer Pump",
    description: "Heavy-duty 12V 8Ah battery agricultural sprayer with stainless steel lance, 4 nozzle attachments, and 4-hour continuous spray.",
    price: 2499,
    comparePrice: 3200,
    category: "Farming Tools",
    subcategory: "Irrigation & Sprayers",
    brand: "AgriTech Power",
    unit: "1 Unit",
    isOrganic: false,
    farmOrigin: "Agri Machinery Division",
    stock: 35,
    rating: 4.8,
    numReviews: 110,
    isFeatured: true,
    images: [{ public_id: "tol1", url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80", altText: "Battery Agricultural Sprayer" }],
    isActive: true
  },
  {
    name: "Automatic Drip Irrigation Kit 50 Plants",
    title: "Complete Drip Irrigation System for Garden & Farm (50 Plants)",
    description: "Water saving kit containing 16mm main line tube, adjustable drippers, T-connectors, water timer adapter, and stakes.",
    price: 899,
    comparePrice: 1299,
    category: "Farming Tools",
    subcategory: "Irrigation & Sprayers",
    brand: "AquaDrip",
    unit: "50 Plants Kit",
    isOrganic: false,
    farmOrigin: "Irrigation Systems Lab",
    stock: 65,
    rating: 4.7,
    numReviews: 145,
    images: [{ public_id: "tol2", url: "https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&w=600&q=80", altText: "Drip Irrigation Kit" }],
    isActive: true
  },

  // Cutting & Pruning
  {
    name: "Professional Japanese Steel Bypass Pruning Shears",
    title: "Heavy Duty Garden Pruning Shear / Secateurs Scissors",
    description: "SK-5 high carbon steel blade secateurs with ergonomic non-slip handles for easy branch trimming and crop harvesting.",
    price: 499,
    comparePrice: 699,
    category: "Farming Tools",
    subcategory: "Cutting & Pruning",
    brand: "ToolCraft Pro",
    unit: "1 Piece",
    isOrganic: false,
    farmOrigin: "Precision Tool Division",
    stock: 90,
    rating: 4.9,
    numReviews: 188,
    isFeatured: true,
    images: [{ public_id: "tol3", url: "https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?auto=format&fit=crop&w=600&q=80", altText: "Pruning Shears" }],
    isActive: true
  },

  // Soil Testing & Protection
  {
    name: "3-in-1 Soil pH, Moisture & Sunlight Meter",
    title: "Digital Soil Tester for Agricultural Soil Health Analysis",
    description: "Battery-free dual probe meter instantly measures soil pH acidity, moisture level percentage, and sunlight intensity.",
    price: 399,
    comparePrice: 599,
    category: "Farming Tools",
    subcategory: "Soil Testing & Care",
    brand: "AgriSense",
    unit: "1 Unit",
    isOrganic: false,
    farmOrigin: "Agri Tech Instruments",
    stock: 80,
    rating: 4.8,
    numReviews: 130,
    images: [{ public_id: "tol4", url: "https://images.unsplash.com/photo-1530836369250-ef72a3f5cda8?auto=format&fit=crop&w=600&q=80", altText: "Soil Meter" }],
    isActive: true
  },
  {
    name: "Organic Vermicompost Bio-Fertilizer",
    title: "Pure Organic Earthworm Vermicompost Fertilizer (5 kg Bag)",
    description: "100% natural bio-fertilizer enriched with nitrogen, phosphorus, micro-nutrients, and beneficial soil microbes.",
    price: 249,
    comparePrice: 350,
    category: "Farming Tools",
    subcategory: "Soil Testing & Care",
    brand: "BioSoil Organics",
    unit: "5 kg Bag",
    isOrganic: true,
    farmOrigin: "Organic Earth Farm",
    stock: 140,
    rating: 4.9,
    numReviews: 215,
    images: [{ public_id: "tol5", url: "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80", altText: "Vermicompost Bag" }],
    isActive: true
  },

  // ── 5. ORGANIC STAPLES ────────────────────────────────────────────────────
  // Ghee & Oils
  {
    name: "Pure A2 Gir Cow Desi Ghee",
    title: "Traditional Bilona Method Pure A2 Gir Cow Ghee (500 ml Glass Jar)",
    description: "Crafted from grass-fed Gir cows using traditional curd-churned Bilona method. Golden color, rich granular texture, and divine aroma.",
    price: 850,
    comparePrice: 1050,
    category: "Organic Staples",
    subcategory: "Ghee & Oils",
    brand: "Vedic Organics",
    unit: "500 ml Jar",
    isOrganic: true,
    farmOrigin: "Gir Organic Dairy, Gujarat",
    stock: 60,
    rating: 5.0,
    numReviews: 290,
    isFeatured: true,
    images: [{ public_id: "stp1", url: "https://images.unsplash.com/photo-1608686207856-001b95cf60ca?auto=format&fit=crop&w=600&q=80", altText: "A2 Desi Cow Ghee" }],
    isActive: true
  },
  {
    name: "Cold Pressed Mustard Oil",
    title: "Wood Pressed Organic Kachi Ghani Mustard Oil (1 Litre)",
    description: "Extracted in traditional wooden Chekku presses at low temperatures to preserve natural pungent aroma, omega-3, and antioxidants.",
    price: 240,
    comparePrice: 290,
    category: "Organic Staples",
    subcategory: "Ghee & Oils",
    brand: "PureHarvest",
    unit: "1 Litre",
    isOrganic: true,
    farmOrigin: "Rajasthan Organic Mills",
    stock: 100,
    rating: 4.8,
    numReviews: 164,
    images: [{ public_id: "stp2", url: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80", altText: "Cold Pressed Mustard Oil" }],
    isActive: true
  },

  // Honey & Sweeteners
  {
    name: "Raw Sundarban Wild Forest Honey",
    title: "Unprocessed Raw Wild Forest Honey (500g Glass Bottle)",
    description: "100% pure raw unpasteurized wild honey collected sustainably by forest tribes. Contains natural pollen, enzymes, and propolis.",
    price: 390,
    comparePrice: 480,
    category: "Organic Staples",
    subcategory: "Honey & Sweeteners",
    brand: "ForestNectar",
    unit: "500g Jar",
    isOrganic: true,
    farmOrigin: "Sundarban Biosphere Reserve",
    stock: 75,
    rating: 4.9,
    numReviews: 210,
    isFeatured: true,
    images: [{ public_id: "stp3", url: "https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=600&q=80", altText: "Raw Forest Honey" }],
    isActive: true
  },
  {
    name: "Organic Chemical-Free Jaggery Powder",
    title: "Natural Sugarcane Jaggery Powder (1 kg Pack)",
    description: "Made from fresh organic sugarcane juice without sulfur or chemical bleaching. Rich in natural iron and minerals.",
    price: 110,
    comparePrice: 140,
    category: "Organic Staples",
    subcategory: "Honey & Sweeteners",
    brand: "SweetEarth",
    unit: "1 kg Pack",
    isOrganic: true,
    farmOrigin: "Kolhapur Sugarcane Farms",
    stock: 120,
    rating: 4.8,
    numReviews: 135,
    images: [{ public_id: "stp4", url: "https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80", altText: "Organic Jaggery Powder" }],
    isActive: true
  },

  // Grains & Flours
  {
    name: "Aged Traditional Basmati Rice",
    title: "1121 Extra Long Grain Premium Aged Basmati Rice (5 kg Bag)",
    description: "Aged for 2 years for aromatic fragrance, slender double-length grains that stay fluffy and non-sticky after cooking.",
    price: 690,
    comparePrice: 850,
    category: "Organic Staples",
    subcategory: "Grains & Flours",
    brand: "Royal Grain Co",
    unit: "5 kg Bag",
    isOrganic: true,
    farmOrigin: "Dehradun Valley",
    stock: 90,
    rating: 4.9,
    numReviews: 195,
    images: [{ public_id: "stp5", url: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80", altText: "Aged Basmati Rice" }],
    isActive: true
  },
  {
    name: "Organic MP Sharbati Whole Wheat Atta",
    title: "100% Stone-Ground Organic Sharbati Wheat Flour (5 kg Bag)",
    description: "Slow stone-milled flour made from golden MP Sharbati wheat. Produces soft, fluffy, nutrient-dense rotis.",
    price: 310,
    comparePrice: 380,
    category: "Organic Staples",
    subcategory: "Grains & Flours",
    brand: "EarthMill Organics",
    unit: "5 kg Bag",
    isOrganic: true,
    farmOrigin: "Sehore, Madhya Pradesh",
    stock: 130,
    rating: 4.8,
    numReviews: 240,
    images: [{ public_id: "stp6", url: "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80", altText: "Organic Sharbati Atta" }],
    isActive: true
  }
];

module.exports = seedCatalogData;
